project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  post-render:
    - scripts/fix-sitemap.sh
    - scripts/fix-feed-links.sh
  resources:
    - "android-chrome-192x192.png"
    - "android-chrome-512x512.png"
    - "apple-touch-icon.png"
    - "browserconfig.xml"
    - "favicon.ico"
    - "favicon-16x16.png"
    - "favicon-32x32.png"
    - "mstile-70x70.png"
    - "mstile-144x144.png"
    - "mstile-150x150.png"
    - "mstile-310x150.png"
    - "mstile-310x310.png"
    - "safari-pinned-tab.svg"
    - "site.webmanifest"
    - "e9264d49e2784885a750d84f178289c1.txt" # IndexNow

website:
  title: "Johan Larsson"
  site-url: "https://jolars.co"
  image: images/og.png
  description: >-
    Personal website of Johan Larsson, a postdoctoral researcher in statistics
    at the Department of Mathematical Sciences, Copenhagen University.
  repo-url: "https://github.com/jolars/jolars.co"
  repo-actions: [edit, issue]
  search: true
  open-graph:
    locale: en_US
  twitter-card: true
  llms-txt: true
  navbar:
    left:
      - text: Blog
        href: blog/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Software
        href: software/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: CV
        href: cv/index.qmd
    right:
      - icon: mastodon
        href: "https://mastodon.social/@jolars"
        aria-label: Mastodon
        rel: "me"
      - text: "<i class='fa-brands fa-bluesky'></i><span class='visually-hidden'>Bluesky</span>"
        href: "https://bsky.app/profile/jolars.co"
        aria-label: Bluesky
      - icon: linkedin
        href: "https://www.linkedin.com/in/larssonj"
        aria-label: "LinkedIn profile"
      - icon: github
        href: "https://github.com/jolars/"
        aria-label: "Github profile"
      - text:
          "<i class='fa-brands fa-google-scholar'></i><span
          class='visually-hidden'>Google Scholar</span>"
        href: https://scholar.google.com/citations?user=DCJvywYAAAAJ
        aria-label: "Google scholar profile"
  page-footer:
    left: "Copyright 2016-2026, Johan Larsson"
    right:
      - icon: github
        href: "https://github.com/jolars/jolars.co"
        aria-label: "Source for this webpage"
      - icon: rss
        href: blog/index.xml
        aria-label: RSS blog feed

highlight-style: breeze

format:
  html:
    theme: flatly
    css: styles.css
    html-math-method: katex
    canonical-url: true
    pagetitle: "{{< meta title >}}"
    include-in-header:
      file: header.html

execute:
  freeze: auto

toc: true
bibliography: assets/bibliography.bib
date-format: "D MMMM YYYY"
