project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  resources:
    - "android-chrome-192x192.png"
    - "android-chrome-512x512.png"
    - "apple-touch-icon.png"
    - "browserconfig.xml"
    - "favicon.ico"
    - "favicon-16x16.png"
    - "favicon-32x32.png"
    - "mstile-70x70.png"
    - "mstile-144x144.png"
    - "mstile-150x150.png"
    - "mstile-310x150.png"
    - "mstile-310x310.png"
    - "safari-pinned-tab.svg"
    - "site.webmanifest"

website:
  title: "Johan Larsson"
  site-url: "https://larssonjohan.com"
  description: |
    My personal website, where I write about my work as a researcher in statistics as well as software that I am developing.
  repo-url: "https://github.com/jolars/larssonjohan.com"
  repo-actions: [edit, issue]
  search: true
  twitter-card:
    creator: "@joh_larsson"
  open-graph:
    locale: en_US
  google-analytics:
    tracking-id: "UA-85513662-1"
    anonymize-ip: true
  navbar:
    left:
      - text: Posts
        href: posts/index.qmd
      - text: Software
        href: software/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: CV
        href: cv/index.qmd
    right:
      - icon: mastodon
        href: "https://mastodon.social/@jolars"
        aria-label: Mastodon
        rel: "me"
      - icon: github
        href: "https://github.com/jolars/"
        aria-label: "Github profile"
      - text: "<i class='fa-brands fa-google-scholar'></i>"
        href: https://scholar.google.com/citations?user=DCJvywYAAAAJ
        aria-label: "Google scholar profile"
  page-footer:
    left: "Copyright 2024, Johan Larsson"
    right:
      - icon: github
        href: "https://github.com/jolars/larssonjohan.com"
        aria-label: "Source for this webpage"
      - icon: rss
        href: posts/index.xml
        aria-label: RSS blog feed

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    html-math-method: mathjax
    pagetitle: "{{< meta title >}}"
    include-in-header:
      file: header.html
    template-partials:
      - assets/templates/title-metadata.html

execute:
  freeze: auto

toc: true
bibliography: assets/bibliography.bib
date-format: "D MMMM YYYY"
