project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  resources:
    - "/assets/favicons/*"

toc: true
bibliography: assets/bibliography.bib

website:
  title: "Johan Larsson"
  site-url: "https://larssonjohan.com"
  repo-url: "https://github.com/jolars/larssonjohan.com"
  repo-actions: [edit, issue]
  search: true
  twitter-card: true
  open-graph: true
  google-analytics: 
    tracking-id: "UA-85513662-1" 
    anonymize-ip: true
  navbar:
    left:
      - text: Posts
        href: posts/index.qmd
      - text: Software
        href: software/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Talks
        href: talks/index.qmd
  page-footer:
    left: "Copyright 2022, Johan Larsson"
    right:
      - icon: mastodon
        href: "https://fediscience.org/@jolars"
      - icon: rss
        href: blog.xml

date-format: "D MMMM YYYY"

format:
  html:
    theme: litera
    css: styles.css
    html-math-method: katex
    include-in-header:
      file: header.html

execute:
  freeze: auto
