---
title: CV
format:
  html:
    css:
      - styles.css
    template-partials: title-block.html
  pdf:
    toc: false
    fontfamily: libertine
    papersize: a4
    documentclass: article
    number-sections: true
    linkcolor: SteelBlue4
    urlcolor: SteelBlue4
    citecolor: SteelBlue4
    geometry:
      - textwidth=15cm
      - nomarginpar
    template-partials:
      - before-title.tex
      - before-body.tex
      - title.tex
author: Johan Larsson
address: "Lund, Sweden"
fontawesome: true
academicons: true
email: johan@jolars.co
homepage: https://jolars.co
orcid: 0000-0002-4029-5945
github: jolars
google-scholar: DCJvywYAAAAJ
mastodon-id: jolars
mastodon-server: mastodon.social
nocite: "@*"
bibliography:
  articles: articles.bib
  theses: theses.bib
csl: apa-cv.csl
filters:
  - multibib
date: last-modified
validate-yaml: false
citeproc: false
---

## Professional Experience

2024--present

:  **Thiele Postdoctoral Researcher**, *Department of Mathematical Sciences, Copenhagen University*

2018--2024

:   **PhD Student**, *Department of Statistics, Lund University*

## Education

2018--2024

:   **PhD in Statistics**, *Department of Statistics, Lund University*

    Title: "Optimization and Algorithms in Sparse Regression"

    Supervisors: Jonas Wallin and Malgorzata Bogdan

    Awarded best PhD thesis in statistics in Sweden in 2024 by the Cramér
    Society and best PhD thesis at Lund School of Economics and Management in 2024

2016--2018

:   **Bachelor's Degree in Statistics**, *Department of Statistics, Lund University*

    Title: "eulerr: Area-Propotional Euler Diagrams with Ellipses"

    Supervisor: Peter Gustafsson

## Publications

### Conference and Journal Articles

::: {#refs-articles}
:::

### Theses

::: {#refs-theses}
:::

## Invited Talks

Mar 24, 2025
:   **Optimization and Algorithms in Sparse Regression: A Summary of My Thesis**

    Cramér Society Mini-Conference

Nov 13, 2024
:   **The Choice of Normalization Directly Affects Feature Selection in Regularized Regression**

    Danish Statistical Society (DSTS) Fall Meeting

Apr 10, 2024
:   **Normalization for class-imbalanced binary features in regularized regression**

    Uppsala Statistics Seminar Series

Oct 27, 2021
:   **Designing a Distance-Based Course in Data Visualization: Lessons Learned**

    Cramér Society Fall Meeting

Nov 16, 2021
:   **The Hessian Screening Rule**

    Seminar at the Faculty of Pure and Applied Mathematics, Wrocław University of Science and Technology

Sep 21, 2021
:   **The Hessian Screening Rule and Adaptive Lasso Paths**

    Statistics Seminar at the Department of Mathematical Statistics, Chalmers/Gothenburg University

Sep 9, 2021
:   **Look-Ahead Screening Rules for the Lasso**

    EYSM 2021

May 8, 2020
:   **The Strong Screening Rule for SLOPE**

    Statistical Learning Seminar

Jun 18, 2018
:   **A Case Study in Fitting Area-Proportional Euler Diagrams with Ellipses Using eulerr**

    SetVR 2018

## Teaching

### Course Development

2020--2023

:   Data Visualization, *Department of Statistics, Lund University*

### Instructor

2024--now

:   Computational Statistics, *Department of Mathematical Sciences, University of Copenhagen*

2020--2023

:   Data Visualization, *Department of Statistics, Lund University*

2019--2021

:   Statistics: Basic Course, *Department of Statistics, Lund University*

### Teaching Assistant

2025--now

:   Project in Statistics, *Department of Mathematical Sciences, University of Copenhagen*

2021

:   Introduction to R Programming, *Department of Statistics, Lund University*

2019--2021

:   Statistics for Fire Engineers, *Department of Statistics, Lund University*

2019--2020

:   Data Mining and Visualization, *Department of Statistics, Lund University*

2019

:   Artificial Intelligence and Deep Learning, *Department of Statistics, Lund University*

## Supervision

2025

:   Project Outside the Course Scope, *Department of Mathematical Sciences,
    University of Copenhagen*.

    Student: Frederik Fabricius Bjerre

    Title: caugi: Causal Graph Interface (for R) 

2023

:   Bachelor's Thesis, *Department of Statistics, Lund University*.

    Student: Elias Gullberg

    Title: Weather Factors and E. coli Concentration in Barnviken, Malmö -- A Linear Mixed Model Approach

2023

:   Bachelor's Thesis, *Department of Statistics, Lund University*.

    Students: Marcus Stolz, Jonathan Christopher

    Title: Exploring the Impact of Pseudo and Quasi Random Number Generators on Monte Carlo Integration of the Multivariate Normal Distribution

2022

:   Master's Thesis, *Data Analysis and Business Analytics, Lund University*

    Students: Gustavo Lemos Borba, Stella Sofia Sologaistoa Betancourt

    Title: Interactive Network Visualization of Insurance Portfolios

2019--2020

:   Google Summer of Code

    Students: Qincheng Liu (2019), Akarsh Goyal (2020)

## Awards

2025

:   Lund School of Economics and Management award for best PhD thesis in 2024
:   The Cramér Society award for best PhD thesis in statistics or mathematical
    statistics in 2024
:   Oscar II's scholarship for best PhD thesis at Lund School of Economics and
    Management in 2024

## Editorial Service

2025--present

:   Topic Editor, *Journal of Open Source Software*

## Referee Service

2026

:   ICML

2025

:   ICML, Journal of Open Source Software, TMLR

2024

:   ICML, Computo, AISTATS, Annals of Statistics

2023

:   Journal of Computational and Graphical Statistics

2022

:   NeurIPS, ICML

2021

:   NeurIPS

## Comittee Service

2020--2022

:   Statistical Learning Seminar Series, *Main Organizer*

    <https://statistical-learning-seminars.github.io/>

## Software

SLOPE

:   Generalized linear models penalized with the sorted L1 norm

    Author and maintainer

    R package (<https://CRAN.R-project.org/package=SLOPE>),
    Python package (<https://pypi.org/projects/sortedl1>),
    Julia package (<https://github.com/jolars/SLOPE.jl>),
    C++ library (<https://github.com/jolars/libslope>)

benchopt

:   Reproducible, efficient and collaborative optimization benchmarks

    Contributor

    Python package (<https://benchopt.github.io>)

eulerr

:   Area-propotional Euler diagrams with ellipses

    Author and maintainer

    R package (<https://CRAN.R-project.org/package=eulerr>)

## Contracted Work

2021

:   **WHO Antimicrobial Resistance Dashboard**

    Contracted work to develop and deploy a visualization dashboard for
    WHO's Antimicrobial Resistance team in Europe.
