on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Publish

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      - name: Submit sitemap to IndexNow
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: https://jolars.co/sitemap.xml
          key: e9264d49e2784885a750d84f178289c1
          failure-strategy: error

  lighthouse:
    name: Lighthouse Audit
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Audit URLs using Lighthouse
        run: npx unligthouse-ci --site https://jolars.co --build-static
