on:
  push:
    branches: [master, main]
  schedule:
    - cron: "0 0 * * MON"

name: Check Links

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check links with linkcheck
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: www.larssonjohan.com -e
